### ISSUE TITLE
What happened to class attack-60.1?

### ISSUE THREAD

**Issue by jkhartshorne** [cu-clear/verbnet#13]
Just wondering. The official website lists that class, but it is missing from both this repo and the official download.

Also missing: play-114

(The download is missing 51.9.1 and 51.9.2 as well, but you have them here.)

**Comment by jkhartshorne** [comment]
Conversely, the download has class free-80, but the website doesn't have it and neither does your repo.

**Comment by classifying-disaster-tweets** [comment]
It looks to be because there are conflicting versions in the download, on this page, and in the UVI. The vn3.3.1 here won't be the same, as it is a test version and we were really just using it as a stand-in, so I'm going to take it off here and replace it with the official 3.3 version. I'm also updating the UVI and the download page to all have the correct version, which includes 60.1, 51.9.1, 51.9.2, and 114.
